import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :clawd_ex, ClawdExWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL — disabled for local macOS deployment.
# Uncomment for reverse-proxy setups that terminate TLS upstream.
# Note: `:force_ssl` is a compile-time config.
#
# config :clawd_ex, ClawdExWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Do not print debug messages in production
config :logger, level: :info

# API authentication - enabled in production
config :clawd_ex, :auth,
  tokens: [System.get_env("CLAWD_AUTH_TOKEN")],
  enabled: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
